using GeneratorWPF.ViewModel._Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace GeneratorWPF.View._Entity
{
    /// <summary>
    /// Interaction logic for EntityList.xaml
    /// </summary>
    public partial class EntityHome : UserControl
    {
        public EntityHome()
        {
            InitializeComponent(); 
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }
    }
}
